version: '3.4'
services:
 database:
   image: mysql:8.0
   expose:
     - "3306"
   ports:
     - "3306:3306"
   restart: always
   volumes:
     - ./database:/var/lib/mysql:rw
   environment:
     MYSQL_USER: root
     MYSQL_PASSWORD: admin
     MYSQL_DATABASE: smarthouse
     MYSQL_ROOT_PASSWORD: admin

 eurekaserver:
   restart: always
   expose:
     - "8761"
   ports:
     - "8761:8761"
   build:
     context: eurekaserver
     dockerfile: Dockerfile

 api-gateway:
   restart: always
   expose:
     - "8080"
   ports:
     - "8080:8080"
   build:
     context: api-gateway
     dockerfile: Dockerfile

 authentication:
   restart: always
   expose:
     - "8081"
   build:
     context: authentication
     dockerfile: Dockerfile

 search:
   restart: always
   expose:
     - "8082"
   build:
     context: search
     dockerfile: Dockerfile

 orderserv:
   restart: always
   expose:
     - "8083"
   build:
     context: orderserv
     dockerfile: Dockerfile

 feedback:
   restart: always
   expose:
     - "8084"
   build:
     context: feedback
     dockerfile: Dockerfile

volumes:
  database: